FROM ruby:2.7.1-alpine
ARG COMMIT=""

RUN apk add --no-cache g++ musl-dev make libstdc++

RUN adduser -D app-user
USER app-user

WORKDIR /home/app-user/app

ENV SERVICE_NAME=sphere
ENV VERSION_SHA=${COMMIT}

ADD ${SERVICE_NAME}/Gemfile ${SERVICE_NAME}/Gemfile.lock ./
RUN bundle install

ENV APP_ENV=production
EXPOSE 4567

COPY --chown=app-user common/ ../common/
COPY --chown=app-user ${SERVICE_NAME}/. .

CMD ruby app.rb